site_name: Typhoon
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'light blue'
  logo: 'img/spin.png'
  favicon: 'img/favicon.ico'
  font:
    text: 'Roboto Slab'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/poseidon'
    - type: 'twitter'
      link: 'https://twitter.com/typhoon8s'
repo_name: 'poseidon/typhoon'
repo_url: 'https://github.com/poseidon/typhoon'
google_analytics:
  - 'UA-38995133-6'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
pages:
  - Home: 'index.md'
  - 'Concepts': 'concepts.md'
  - 'AWS': 'aws.md'
  - 'Bare-Metal': 'bare-metal.md'
  - 'Digital Ocean': 'digital-ocean.md'
  - 'Google Cloud': 'google-cloud.md'
  - 'Addons':
    - 'Overview': 'addons/overview.md'
    - 'CLUO': 'addons/cluo.md'
    - 'Heapster': 'addons/heapster.md'
    - 'Nginx Ingress': 'addons/ingress.md'
    - 'Prometheus': 'addons/prometheus.md'
    - 'Grafana': 'addons/grafana.md'
  - 'Topics':
    - 'Maintenance': 'topics/maintenance.md'
    - 'Hardware': 'topics/hardware.md'
    - 'Security': 'topics/security.md'
    - 'Performance': 'topics/performance.md'
  - 'FAQ': 'faq.md'
  - 'Advanced':
    - 'Customization': 'advanced/customization.md'
