site_name: Typhoon
site_description: A minimal and free Kubernetes distribution
site_author: Dalton Hubble
copyright: Poseidon Laboratories
repo_name: poseidon/typhoon
repo_url: https://github.com/poseidon/typhoon
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
  logo: 'img/spin.png'
  favicon: 'img/favicon.ico'
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    primary: blue
    accent: pink
  font:
    text: 'Roboto Slab'
    code: 'Roboto Mono'
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/poseidon
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/typhoon8s
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - Home: 'index.md'
  - 'Announce': 'announce.md'
  - 'Architecture':
    - 'Concepts': 'architecture/concepts.md'
    - 'Operating Systems': 'architecture/operating-systems.md'
    - 'AWS': 'architecture/aws.md'
    - 'Azure': 'architecture/azure.md'
    - 'Bare-Metal': 'architecture/bare-metal.md'
    - 'DigitalOcean': 'architecture/digitalocean.md'
    - 'Google Cloud': 'architecture/google-cloud.md'
  - 'Fedora CoreOS':
    - 'AWS': 'fedora-coreos/aws.md'
    - 'Azure': 'fedora-coreos/azure.md'
    - 'Bare-Metal': 'fedora-coreos/bare-metal.md'
    - 'DigitalOcean': 'fedora-coreos/digitalocean.md'
    - 'Google Cloud': 'fedora-coreos/google-cloud.md'
  - 'Flatcar Linux':
    - 'AWS': 'flatcar-linux/aws.md'
    - 'Azure': 'flatcar-linux/azure.md'
    - 'Bare-Metal': 'flatcar-linux/bare-metal.md'
    - 'DigitalOcean': 'flatcar-linux/digitalocean.md'
    - 'Google Cloud': 'flatcar-linux/google-cloud.md'
  - 'Topics':
    - 'Maintenance': 'topics/maintenance.md'
    - 'Hardware': 'topics/hardware.md'
    - 'Security': 'topics/security.md'
    - 'Performance': 'topics/performance.md'
    - 'FAQ': 'topics/faq.md'
  - 'Advanced':
    - 'Overview': 'advanced/overview.md'
    - 'ARM64': 'advanced/arm64.md'
    - 'Customization': 'advanced/customization.md'
    - 'Nodes': 'advanced/nodes.md'
    - 'Worker Pools': 'advanced/worker-pools.md'
  - 'Addons':
    - 'Overview': 'addons/overview.md'
    - 'Nginx Ingress': 'addons/ingress.md'
    - 'Prometheus': 'addons/prometheus.md'
    - 'Grafana': 'addons/grafana.md'
    - 'fleetlock': 'addons/fleetlock.md'
